twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@TigrisCore/form/daisyui.html.twig'
        - '@TigrisCore/form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
